system_status.settings:
  type: config_object
  label: 'System status settings'
  mapping:
    system_status_token:
      type: string
    system_status_encrypt_token:
      type: string
    system_status_service_allow_external:
      type: boolean
